language: python
services:
  - docker
install:
  - make deps
script:
  - make lint
  - make test
after_success:
  - make docker_build
deploy:
  provider: heroku
  app: young-headland-67045
  api_key: ${HEROKU_API_KEY}
